seed: 1
indv_eps: 60
env_name: 'Carrier-v0'
batch_mode: True
from_exp: 'test_pusher'
controller_reoptimized: False

fitness_type: "reward"
rewardDomain: [0., 10.]

features_list:  ["actuation", "emptiness"]
lengthDomain: [1, 5]
heightDomain: [1, 5]
baseLengthDomain: [0, 5]
emptinessDomain: [0., 1.]
actuationDomain: [0., 1.]
verticalActuationDomain: [0., 1.]
horizontalActuationDomain: [0., 1.]
compactnessDomain: [0., 1.]
elongationDomain: [0., 1.]

containers:
    cont0:
        type: Grid                       # The type of the container (e.g. Grid, CVTGrid, Container, NoveltyArchive, ...)
        name: cont0                      # The name of the container. Optional. Default to the parent key (here also 'cont0')
        shape: [10, 10]                  # The number of bins for each feature
        max_items_per_bin: 1             # The number of items in each bin of the grid

main_algorithm_name: algoTotal

algorithms:
    # Default parameter values for each algorithm
    optimisation_task: max              # maximisation of all fitness objectives
    container: cont0                    # container to use to store individuals told to the optimisers
    shape: [5, 5]                       # shape of individual body

    algoInit:
        type: Random
        budget: 500                     # The total number of allowed evaluations
        batch_size: 28

    algoQD:
        type: Mutation
        budget: 1500                     # The total number of allowed evaluations
        batch_size: 28
    
    algoTotal:
        type: Sq                        # Sequence (Sq) of algorithms to execute them one after the other
        algorithms: ['algoInit', 'algoQD']
        tell_container_when_switching: only_best